# -*- coding: utf-8 -*-
"""titanic_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/srishtidyadav/titanic-1.cffd81f9-84ee-42f0-a56d-d99ccaf6d8be.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260119/auto/storage/goog4_request%26X-Goog-Date%3D20260119T175343Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5fb1dbdc3438798082e83040fb2024cf7f0bc0cdb60e1657c04a231137cdae278db95f9bf6781b18d050faad5593104abb63122441da3ecff2d0069d09375e6e58a52c1849d56be3f9c60d82aadab112f2d774889e50e82d20d970d9785003f5f629d8e0aeca4fb9e799949eccc3d52d4354b28e8dabb42d0a158ca1e660508c009a1fbc13aab8a2882bb4b8fee642db97d4ed6936fcf8ad3e65bbc223153abdc72030e743e099b9565aa837fbd5f6e8e2b40d507e1acee2f16c41a54c6c88184a1d949bfe47beb063b903a9c8486fed304b768aaf1eb45fbebec6fde21d2f45c72e09dee3704a9f3a68e3f6e47fbe81ba58bfd04ad9da78a246dc7cab9c9fbd
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

titanic_path = kagglehub.competition_download('titanic')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv("/kaggle/input/titanic/train.csv")
train.head()

train.shape

train.info()

train.describe()

train.isnull().sum()

sns.countplot(x='Survived', data=train)
plt.title("Survival Count")
plt.show()

sns.countplot(x='Sex', hue='Survived', data=train)
plt.title("Survival by Gender")
plt.show()

sns.histplot(train['Age'], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

sns.boxplot(x='Survived', y='Fare', data=train)
plt.show()

sns.countplot(x='Survived', hue='Pclass', data=train)
plt.title("Survival by Pclass")
plt.show()

sns.histplot(x='Age', hue='Survived',data=train)
plt.title("Age Distribution")
plt.show()

sns.histplot(x='Fare', hue='Survived',data=train)
plt.title("Age Distribution")
plt.show()

train['FamilySize'] = train['SibSp'] + train['Parch'] + 1
train['IsAlone'] = train['FamilySize'] == 1
train.groupby('IsAlone')['Survived'].mean()

train['FamilySize'] = train['SibSp'] + train['Parch'] + 1

import matplotlib.pyplot as plt

train.groupby('FamilySize')['Survived'].mean().plot(kind='bar')
plt.xlabel('Family Size')
plt.ylabel('Survival Rate')
plt.title('Survival Rate by Family Size')
plt.show()

import pandas as pd
from sklearn.linear_model import LogisticRegression

# Load data
train = pd.read_csv("/kaggle/input/titanic/train.csv")
test = pd.read_csv("/kaggle/input/titanic/test.csv")

# Encode Sex (future-proof)
train['Sex'] = train['Sex'].map({'male': 0, 'female': 1})
test['Sex'] = test['Sex'].map({'male': 0, 'female': 1})

# Fill missing values (NO inplace, NO chained assignment)
train['Age'] = train['Age'].fillna(train['Age'].median())
test['Age'] = test['Age'].fillna(test['Age'].median())

train['Fare'] = train['Fare'].fillna(train['Fare'].median())
test['Fare'] = test['Fare'].fillna(test['Fare'].median())

# Select features
features = ['Pclass', 'Sex', 'Age', 'Fare']
X = train[features]
y = train['Survived']
X_test = test[features]

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X, y)

# Predict
predictions = model.predict(X_test)

submission = pd.DataFrame({
    'PassengerId': test['PassengerId'],
    'Survived': predictions
})

submission.to_csv("/kaggle/working/submission.csv", index=False)